### ISSUE TITLE
async logger + slog_stdlog never flushes

### ISSUE THREAD

**Issue by scottlamb** [slog-rs/slog#118] opened 2017-03-06 16:15 UTC
I have this test program:

```rust
#[macro_use] extern crate log;
extern crate slog;
extern crate slog_envlogger;
extern crate slog_stdlog;
extern crate slog_term;

use slog::DrainExt;

fn main() {
    let drain = slog_term::StreamerBuilder::new().stderr().async().full().build();
    slog_stdlog::set_logger(slog::Logger::root(slog_envlogger::new(drain).ignore_err(),
                                               None)).unwrap();
    info!("exiting.");
}
```

compiled with these dependencies:

```
[dependencies]
log = "0.3"
slog = "1.5"
slog-envlogger = "0.5"
slog-stdlog = "1.1"
slog-term = "1.3"
```

If I run it with `RUST_LOG=info` set, I don't see the `exiting.` log line (at least, not consistently). I do if I remove the `.async()`.

It looks like `slog-async::AsyncCore` (used internally by `slog-term`) has a `Drop` trait which flushes the async logger. But it's never run. A logger installed with `slog_stdlog` is never destroyed.

IMHO, the best solution to this would be for a logger to not be permanently async. Rather, when you install a logger, you get some handle which you can use to make it async in a scoped way. When leaving the scope, it flushes and reverts to sync, so log messages are never dropped.

**Comment by dpc** [comment] 2017-03-06 17:52
Ha. Thank you for reporting it! I have noticed that yesterday evening when porting and testing crates to slog  v2, but did not have a chance to fill an issue or investigate.

I was thinking about just removing `slog_stdlog::set_logger`/`slog-scope::set_logger` call and everything will always have to be called through the scope so no globals/statics are involved.

I need to investigate more.

BTW. I think in your investigation you might have looked at some crates from slog v1, and some from v2. The exact structure and interactions changed a bit, so it might be a bit confusing. Sorry for that! And I advise just being cautios about v1 vs v2.

**Comment by dpc** [comment] 2017-03-08 04:54
So after some though I am still thinking that removing `slog_scope::set_global_logger` is the way to go. Thoughts?

**Comment by scottlamb** [comment] 2017-03-08 05:15
I'm confused. How would this interact with the `log` crate's interface? In the `slog-scope-stdlog` (which I guess is is the v2 stuff):

```
pub fn init() -> Result<(), log::SetLoggerError> {
    log::set_logger(|max_log_level| {
        max_log_level.set(log::LogLevelFilter::max());
        Box::new(Logger)
    })
}
```

doesn't the `Logger` have to live forever? how does removing `set_global_logger` change that?

**Comment by dpc** [comment] 2017-03-08 06:24
The logger set in the above function is a different [`Logger`](https://github.com/slog-rs/stdlog/blob/2b93fdf9fd3886b7c3d74b84c64f1659d293366f/lib.rs#L65). So every `info!` from legacy `log` crate is processed by [`Logger::log`](https://github.com/slog-rs/stdlog/blob/2b93fdf9fd3886b7c3d74b84c64f1659d293366f/lib.rs#L83) function. That function uses [`with_current_logger`](https://github.com/slog-rs/stdlog/blob/2b93fdf9fd3886b7c3d74b84c64f1659d293366f/lib.rs#L201) to look up the `slog`'s `Logger` to forward the messages to.

So `init` will still setup global `log`'s `Logger`, but there will be no global [`GLOBAL_LOGGER`](https://github.com/slog-rs/stdlog/blob/2b93fdf9fd3886b7c3d74b84c64f1659d293366f/lib.rs#L54) to [fallback to](https://github.com/slog-rs/stdlog/blob/2b93fdf9fd3886b7c3d74b84c64f1659d293366f/lib.rs#L207). The root of the problem is that `lazy_static` never gets a destructor called so async thread might be killed before having a chance to flush all the messages.

**Comment by scottlamb** [comment] 2017-03-09 03:44
Oh, I see thanks. So on a thread that hasn't specifically set up a logging scope, such as one created by a slog-unaware library, the standard logging routines would do nothing? Hmm, that's not too appealing to me. But I have a confession to make: I'm not really into structured logging at all (I only use slog because it was the first logging crate I found that did async). Maybe for people who are taking more advantage of it and adding key/value pairs to their scopes that makes more sense. It's possible I'm just using the wrong crate for my purposes.

**Comment by dpc** [comment] 2017-03-09 04:13
Oh... right. The whole reason why the global was there, was just in case to catch the thread's that couldn't setup their own scope. Ehhh... I dislike the whole `slog-scope` because globals are evil. :D 

Sure, if you really want to have just simple global logger, you might look for something else. But the problem (one of the problems) with `log` based loggers is they are not composable: some will have feature A, some feature B, some C, and there's no way to use them together.

Well, the workaround for your current problem is probably just adding `thread::sleep` for couple of milliseconds at the end of main until I figure out better api.

**Comment by vorner** [comment] 2017-03-27 07:44
I hit the same problem recently. My solution was to place a guard object in the `main` and reset the global logger to a new `Logger::root(Discard, o!())` when it is dropped. Then the usual `drop` on the async logger gets called.

I'm not sure something can be done to fix the real problem on the library side. But I'd propose adding a note to the documentation with some suggested workaround, so people are aware of it and don't spend hours looking why some messages didn't make it.

**Comment by scottlamb** [comment] 2017-03-28 03:53
fwiw, I tried out the approach I mentioned in a (non-slog) simple logging crate:

> IMHO, the best solution to this would be for a logger to not be permanently async. Rather, when you install a logger, you get some handle which you can use to make it async in a scoped way. When leaving the scope, it flushes and reverts to sync, so log messages are never dropped.

I'm happy with it. Source [here](https://github.com/scottlamb/mylog/blob/master/src/lib.rs); the gist is that you build a `Handle` (which is really just an `Arc<Logger>`); in addition to a method which installs that with `log::set_logger_raw`, there's one that returns an `AsyncHandle`. The logger is async until the `AsyncHandle` is dropped, then it's flushed and reverted to sync.

I like this because you don't have a point where you arbitrary start discarding stuff, but you still get async while your program is doing most of its work.

**Comment by dpc** [comment] 2017-03-28 04:00
I have just published `slog-scope = 2.0.0-3.0` with a guard implementation. Please let me know how you like it. It can be changed to something else if it doesn't work well. https://github.com/slog-rs/scope/commit/92c5e454f5f29e7dad69849b66461b2f2088834e

**Comment by dpc** [comment] 2017-03-28 04:13
https://docs.rs/slog-scope/2.0.0-3.0/slog_scope/fn.set_global_logger.html

**Comment by vorner** [comment] 2017-03-28 07:45
Thanks, it does work (and it even warns for an unused result :-).

**Comment by dpc** [comment] 2017-03-29 06:22
Closing for now. Feel free to keep commenting or reopen if needed.

**Closed by dpc** 2017-03-29 06:22 UTC
