### ISSUE TITLE
slog_stream and  slog_term format reuse, especially for timestamp

### ISSUE THREAD

**Issue by sbant** [slog-rs/slog#97] opened 2016-12-29 08:59 UTC
Like code below, there are two identical timestamp format for file and console, I think the timestamp will called twice. 

Can this be avoid?

```
struct MyFormat;

impl slog_stream::Format for MyFormat {
    fn format(&self, io: &mut io::Write, rinfo: &slog::Record, _logger_values: &slog::OwnedKeyValueList) -> io::Result<()> {
        let msg = format!("{};{};{};{};{};{}\r\n", 
            chrono::Local::now().format("%Y-%m-%d %H:%M:%S.%f"),
            rinfo.level(),
            thread::current().name().unwrap_or("<unnamed>"),
            rinfo.line(),
            rinfo.module(),
            rinfo.msg());
        io.write_all(msg.as_bytes())?;
        
        Ok(())
    }
}

fn timestamp_local(io: &mut io::Write) -> io::Result<()> {
    write!(io, "{}", chrono::Local::now().format("%Y-%m-%d %H:%M:%S.%f"))
}

fn init_log() {
    let file = OpenOptions::new()
        .create(true)
        .append(true)
        .open("log/main.log").unwrap();

    let file_drain = slog_stream::async_stream(file, MyFormat);
    let console_drain = slog_term::StreamerBuilder::new().use_custom_timestamp(timestamp_local).async().build();
    
    let logger = slog::Logger::root(slog::duplicate(file_drain, console_drain).fuse(), o!());

    slog_scope::set_global_logger(logger);
}
```

**Comment by dpc** [comment] 2016-12-29 19:09
Yes, you're right that each drain will do timestamp formatting on it's own.

If it so happens that you're using the same formatting for both and you're really going for the speed there are couple of approaches you could take.

1. Write a custom drain that formats once while writes to both console and terminal. By copying existing slog code which is liberally licensed this should be quite fast.

2. Use caching; something like a `thread_local` static tuple `(timestamp, it's string)`, and compare if timestamp is still the same before doing the actual formatting again. In case you log a lot of things in burst, that could save you even more time.

2 is probably way better.

BTW. (unrelated to you main problem)

Note, in `MyFormat` it's probably better to use `write!()` instead of allocating string, and then writing it.

Note, maybe you can reuse term format with https://docs.rs/slog-term/1.3.4/slog_term/struct.Format.html instead of implementing `MyFormat`.

**Comment by sbant** [comment] 2016-12-30 03:31
I mean, if slog can call chrono::Local::now() only once, and use the timestamp with unlimit drains registered with slog.

**Comment by dpc** [comment] 2016-12-30 06:26
Please note that timestamp in slog is just a value like any other and core `slog` does not deal with time at all - by design.  What you describe would impose taking the timestamp at least once at a fixed place, and would force a timestamp library/standard on the user.

`slog` core library is trying to be as flexible and lightweight as possible. The other `slog-*` crates are some default blocks that you can use, but you don't have to.

For most apps calling `now()` multiple times, and formatting it in multiple drains is not a problem. For the ones that care, there are plenty of ways to optimize it even further then you're asking for. Eg. one could have a separate thread running in a loop, formatting the timestamp to atomically swapped string. Or you can create a drain that formats the timestamp only once (to string), then call multiple other drains that do not add their own timestamps etc. It should be relatively easy to do so. Other ways could be invented as well.

So if you're in need to optimize here, I'd advise writing your own `Drain` implementation that does exactly what you want.

**Comment by sbant** [comment] 2016-12-30 06:44
I just use slog, and use the slog_stream and slog_term with it, now I know there relationship.

Thanks for your advice.

**Comment by sbant** [comment] 2016-12-30 08:52
I've tried and looked at the code in slog-term
pub fn build(self) -> Box<slog::Drain<Error = io::Error> + Send + Sync>
just build a Drain.

Thus, if I need two or more output at the same time, I still need register two or more drains with slog::logger, own Drain implementation can't solve the problem.

**Comment by dpc** [comment] 2016-12-30 08:55
Yes, you can't just reuse `slog-term` in such case since it's adding it's own timestamp anyway.

**Comment by dpc** [comment] 2016-12-30 08:58
You could reuse it's source code though.

**Comment by dpc** [comment] 2017-01-01 23:24
How did it go? I'm closing the issue, but feel free to reopen or keep commenting here or on gitter.

**Closed by dpc** 2017-01-01 23:24 UTC

**Comment by sbant** [comment] 2017-01-16 07:29
I just copy the code from slog-stream, modified the Streamer struct with file_io and console_io, change the log function to write to both file and console with same format, at least works for me...
