### ISSUE TITLE
Making Logger unwind safe

### ISSUE THREAD

**Issue by jsgf** [slog-rs/slog#111] opened 2017-02-09 19:16 UTC
Right now trying to use a Logger within a `std::panic::catch_unwind` block fails to compile with
```
the trait `std::panic::RefUnwindSafe` is not implemented for `slog::ser::SyncMultiSerialize + 'static`
```

I can use `AssertUnwindSafe`, but I'm not sure if that's actually true.

Is there currently a way to use slog safely in this case, or if not, could there be?

**Comment by dpc** [comment] 2017-02-09 21:45
I need to do some homework on uniwind safety. IIRC, it's about adding a marker trait here and there if types are indeed unwind safe. I think all serializable key&values that slog supports should be.

Thank you for reporting it and please remind me in case I don't get back to you until the end of the weekend.

**Comment by dpc** [comment] 2017-02-12 06:09
So they way I understand it, I'll have to add `UnwindSafe` bound on some of the traits that users can implement for key-value pairs.

I'm in the middle of some other stuff, but let's keep it open.

**Comment by dpc** [comment] 2017-02-19 22:59
This will be fixed in `slog v2` (actually next alpha release of it). Please test at first opporunity (when all drains you need will be ported to slog v2).

**Comment by dpc** [comment] 2017-02-24 05:44
`slog v2.0.0-alpha2` has been released. There are some compiler regressions (see https://github.com/slog-rs/slog/issues/115) and it's generally PITA because all trait objects now require a `UnwindSafe` qualifier which sometimes needs to be done through a separate `trait`, but oh well...

Closing. Feel free to reopen in case of troubles.

**Closed by dpc** 2017-02-24 05:44 UTC
